### PR TITLE
Pass along the authorizer type to the Swagger template

### PR DESCRIPTION
**Pull request by szilveszter**
This way we could also use `request` type custom authorizers.

### CODE REVIEW

**Comment by ryandub** [comment]
Thanks @szilveszter ! Are there any other variables we need for `Request` type authorizers?

**Comment by szilveszter** [comment]
The `request` type authorizers use a subset of the `token` types' config variables, so we should be covered with this change.

**Comment by ryandub** [comment]
In one example I have from another project, I have the following:

```
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      type: "request"
      identitySource: "method.request.header.${authorizer_header}"
      authorizerUri: "${authorizer_arn}"
      authorizerCredentials: "${authorizer_role}"
      identityValidationExpression: "${authorizer_expression}"
      authorizerResultTtlInSeconds: ${authorizer_ttl}
```

Seems like you might want to support `identitySource` too right? https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html

**Comment by szilveszter** [comment]
Yes, I have indeed missed that one. Will open a follow-up PR soon, I'm glad you did not trust my earlier response :)

**Pull request merged**
